version: '3.3'

services:
  
 
  bark_server:
    build: .
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    container_name: bark_prompt
    restart: always
    volumes:
      - .:/usr/src/app